version: "3.11"
services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    # env_file:
    #   - ./config/.env
    ports:
      - "8000:8000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/frontend-client/Dockerfile
    # image: ap-backend:v1
    restart: always
    # env_file:
    #   - ./config/.env
    ports:
      - "5173:5173"
  