version: "3.11"
services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    # env_file:
    #   - ./config/.env
    ports:
      - "8000:8000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: always
    # env_file:
    #   - ./config/.env
    ports:
      - "5173:5173"
  