# Generated by Django 4.2.1 on 2023-05-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.URLField(max_length=2048)),
                ("title", models.TextField(max_length=255)),
                ("brand", models.TextField(max_length=255)),
                ("description", models.TextField(max_length=2048)),
                ("price", models.IntegerField()),
                ("category", models.TextField(max_length=255)),
                ("thumbnail", models.URLField(max_length=2048)),
            ],
        ),
    ]
